import type { Metadata } from "next";
import "./globals.css";
import { Navigation } from "@/components/layout/nav";
import { outfit } from "@/components/fonts";
import { Footer } from "@/components/layout/footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${outfit.className} antialiased`}>
        <div className="h-full w-[93%] mx-auto pb-12 pt-7">
          <Navigation />
          <main className="py-12 xl:w-[82%] mx-auto md:w-[90%] w-full">{children}</main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
